# Generated by Django 4.2.23 on 2025-08-23 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('Experience', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovtPolicyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PolicyName', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='govt_policies/')),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Passsword', models.CharField(blank=True, max_length=100, null=True)),
                ('Userrole', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Dob', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Phoneno', models.CharField(blank=True, max_length=15, null=True)),
                ('Loginid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Feedback', models.TextField(blank=True, null=True)),
                ('Docid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.doctortable')),
                ('Userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Medicine', models.TextField(blank=True, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('Docid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.doctortable')),
                ('Patientid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('Createdate', models.DateField(blank=True, null=True)),
                ('Docid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.doctortable')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacistTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Phoneno', models.CharField(blank=True, max_length=15, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('Loginid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, null=True)),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Patientid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('PharmacyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.pharmacisttable')),
            ],
        ),
        migrations.AddField(
            model_name='doctortable',
            name='Loginid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.logintable'),
        ),
        migrations.CreateModel(
            name='BookmedicineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Medicineid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.medicinetable')),
                ('Patientid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('Token', models.IntegerField(blank=True, null=True)),
                ('Docid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.doctortable')),
                ('Patientid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.usertable')),
            ],
        ),
    ]
