# Generated by Django 4.2.23 on 2025-08-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmenttable',
            old_name='Patientid',
            new_name='Userid',
        ),
        migrations.RenameField(
            model_name='bookmedicinetable',
            old_name='Patientid',
            new_name='Userid',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Patientid',
            new_name='Userid',
        ),
        migrations.RenameField(
            model_name='prescriptiontable',
            old_name='Patientid',
            new_name='Userid',
        ),
        migrations.AddField(
            model_name='doctortable',
            name='Phoneno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
