# Generated by Django 4.2.23 on 2025-09-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0002_rename_patientid_appointmenttable_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('doc_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.doctortable')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.usertable')),
            ],
        ),
    ]
