# Generated by Django 4.2.23 on 2025-09-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0003_reviewtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptiontable',
            name='Medicine',
        ),
        migrations.RemoveField(
            model_name='prescriptiontable',
            name='Quantity',
        ),
    ]
