# Generated by Django 4.2.23 on 2025-09-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0004_remove_prescriptiontable_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Docid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.doctortable'),
        ),
        migrations.AlterField(
            model_name='posttable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='add_post/'),
        ),
    ]
