# Generated by Django 4.2.23 on 2025-09-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0005_notification_docid_alter_posttable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
