# Generated by Django 4.2.23 on 2025-09-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0006_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetable',
            name='ExpiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinetable',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_images/'),
        ),
        migrations.AddField(
            model_name='medicinetable',
            name='Stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
