# Generated by Django 4.2.23 on 2025-10-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0007_medicinetable_expirydate_medicinetable_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiontable',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='prescriptiontable',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
