# Generated by Django 4.2.23 on 2025-10-19 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0008_prescriptiontable_image_prescriptiontable_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetable',
            name='Company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('MedicineName', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Company', models.CharField(blank=True, max_length=100, null=True)),
                ('ExpiryDate', models.DateField(blank=True, null=True)),
                ('PharmacyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.pharmacisttable')),
            ],
        ),
    ]
