# Generated by Django 4.2.23 on 2025-10-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0009_medicinetable_company_ordertable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='PharmacyId',
        ),
    ]
