# Generated by Django 4.2.23 on 2025-10-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0010_remove_ordertable_pharmacyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
