# Generated by Django 4.2.23 on 2025-10-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0011_ordertable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='OrderDate',
            field=models.DateField(auto_now_add=True, default='2025-10-19'),
            preserve_default=False,
        ),
    ]
