# Generated by Django 4.2.23 on 2025-10-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0012_ordertable_orderdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='PharmacyId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.pharmacisttable'),
        ),
    ]
