# Generated by Django 4.2.23 on 2025-10-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0013_ordertable_pharmacyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='Status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
