# Generated by Django 4.2.24 on 2025-10-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0014_alter_ordertable_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenttable',
            name='Department',
        ),
    ]
