# Generated by Django 4.2.24 on 2025-10-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0015_remove_appointmenttable_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacisttable',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
