# Generated by Django 4.2.24 on 2025-10-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0016_pharmacisttable_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertable',
            old_name='Company',
            new_name='Days',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='ExpiryDate',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='MedicineName',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='ordertable',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='Perscription',
            field=models.FileField(blank=True, null=True, upload_to='Prescription'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='USERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.usertable'),
        ),
    ]
