# Generated by Django 4.2.26 on 2025-11-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0017_rename_company_ordertable_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiontable',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
