# Generated by Django 4.2.26 on 2025-11-20 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0018_alter_prescriptiontable_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.usertable')),
            ],
        ),
    ]
