# Generated by Django 4.2.26 on 2025-11-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0019_historytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_age', models.CharField(blank=True, max_length=10, null=True)),
                ('father_age', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_age', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('genes_mother_side', models.CharField(blank=True, max_length=50, null=True)),
                ('inherited_father', models.CharField(blank=True, max_length=50, null=True)),
                ('maternal_gene', models.CharField(blank=True, max_length=50, null=True)),
                ('paternal_gene', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_cell_count', models.CharField(blank=True, max_length=20, null=True)),
                ('white_blood_cell_count', models.CharField(blank=True, max_length=20, null=True)),
                ('respiratory_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('parental_consent', models.CharField(blank=True, max_length=10, null=True)),
                ('follow_up', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_effects', models.CharField(blank=True, max_length=100, null=True)),
                ('folic_acid_intake', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_test_result', models.CharField(blank=True, max_length=50, null=True)),
                ('No_of_previous_abortion', models.CharField(blank=True, max_length=10, null=True)),
                ('genetic_disorder', models.CharField(max_length=200)),
                ('disorder_subclass', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
