# Generated by Django 4.2.26 on 2025-11-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesentryapp', '0020_geneticprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticprediction',
            name='USERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genesentryapp.usertable'),
        ),
    ]
